title: Minty
email: kabirgoel.kg@gmail.com
description: >
  A refreshingly simple way to work.
baseurl: "/minty"
url: "http://kabirgoel.com"
twitter_username: notkabir
github_username: kbrgl

# Build settings
markdown: kramdown